package com.example.epolisplusapp.models.cabinet

data class Response(
    val ADDRESS: String,
    val BIRTHDAY: String,
    val BODY_NUMBER: String,
    val ENGINE_NUMBER: String,
    val ERROR: String,
    val ERROR_MESSAGE: String,
    val FIRST_NAME: String,
    val FY: String,
    val INN: String,
    val ISSUE_YEAR: String,
    val LAST_NAME: String,
    val MARKA_ID: String,
    val MIDDLE_NAME: String,
    val MODEL_ID: String,
    val MODEL_NAME: String,
    val ORGNAME: String,
    val PASSPORT_ISSUED_BY: String,
    val PASSPORT_ISSUE_DATE: String,
    val PASSPORT_NUMBER: String,
    val PASSPORT_SERIES: String,
    val PINFL: String,
    val REGION_NAME: String,
    val SEATS: String,
    val TECH_PASSPORT_ISSUE_DATE: String,
    val USE_TERRITORY: String,
    val VEHICLE_TERRITORY_ID: String,
    val VEHICLE_TYPE_ID: String,
    val VEHICLE_TYPE_NAME: String
)